# Generated by Django 6.0.6 on 2026-06-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_invoice_discount_amount_billingpolicy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingpolicy',
            name='additional_class_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='% off per_session_rate for 2nd+ enrolled classes (e.g. 50 = half price)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='billingpolicy',
            name='per_session_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate per session for the first enrolled class', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='billingpolicy',
            name='pricing_model',
            field=models.CharField(choices=[('flat', 'Flat rate'), ('per_session', 'Per session')], default='flat', max_length=20),
        ),
        migrations.AlterField(
            model_name='billingpolicy',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
