# Generated by Django 6.0.7 on 2026-08-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='overpayment_credited',
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8,
                help_text="How much of this invoice's overpayment (if any) has already been "
                          "pulled into a later invoice for the same member as a discount.",
            ),
        ),
    ]
