# Generated by Django 6.1 on 2026-08-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_invoice_overpayment_credited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
