# Generated by Django 6.0.7 on 2026-08-21 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('classes', '0007_class_default_leader'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassHelper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpers', to='classes.class')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helping_classes', to='members.member')),
            ],
            options={
                'ordering': ['member__name'],
                'unique_together': {('assigned_class', 'member')},
            },
        ),
        migrations.CreateModel(
            name='SessionHelper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False)),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helped_sessions', to='members.member')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_helpers', to='classes.session')),
            ],
            options={
                'ordering': ['helper__name'],
                'unique_together': {('session', 'helper')},
            },
        ),
    ]
