# Generated by Django 6.1 on 2026-09-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0005_syllabussubsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabussubsection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
