# Generated by Django 6.0.7 on 2026-07-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_familygroup_familygroupmember_familygroup_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
